---
- name: restart tomcat
  service:
    name: tomcat8
    state: restarted

- name: restart guacd
  service:
    name: guacd
    state: restarted
      
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes